apiVersion: scale.spectrum.ibm.com/v1beta1
kind: LocalDisk
metadata:
  name: shareddisk-drbd
  namespace: ibm-spectrum-scale
spec:
  device: {{ iscsi_ha_device }}
  node: {{ worker_nodes[0] }}
  # nodeConnectionSelector defines the nodes that have the shared lun directly attached to them
  nodeConnectionSelector:
    matchExpressions:
    - key: node-role.kubernetes.io/worker
      operator: Exists

  # set below only during testing
  existingDataSkipVerify: true
