---
apiVersion: v1
kind: Namespace
metadata:
  name: iscsi-hatest-deployment
spec:
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-ha-scale-claim
  namespace: iscsi-hatest-deployment
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: iscsi-ha-sc
  resources:
    requests:
      storage: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: writer
  name: writer
  namespace: iscsi-hatest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: writer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: writer
    spec:
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: test-ha-scale-claim
      containers:
      - name: writer
        image: alpine
        command: ["/bin/sh", "-c", "touch /mnt/log/txt; i=$(awk 'END{print (NR ? $1 : 0)}' /mnt/log.txt 2>/dev/null); while true; do let i++; echo $i -- $(date +%Y/%m/%d-%H:%M:%S) >> /mnt/log.txt; sleep .01; done"]
        volumeMounts:
          - name: shared-volume
            mountPath: "/mnt"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: reader
  name: reader
  namespace: iscsi-hatest-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reader
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: reader
    spec:
      volumes:
      - name: shared-volume
        persistentVolumeClaim:
          claimName: test-ha-scale-claim
      containers:
      - name: reader
        image: alpine
        command: ["/bin/sh", "-c", "while true; do tail -f /mnt/log.txt; sleep .01; done"]
        volumeMounts:
          - name: shared-volume
            mountPath: "/mnt"
